# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d683c79d384a60729c4eea01e96600e0ea0cca946ef18f6b9a2fa629bc66020b0947fa8e7b88151ef0f12ab210626f08d191f1f2c0055ed2955422cab5e1782

test:
  secret_key_base: c160b07f4c57f8e2062caf918a04aebbe065bf2cfb5c4716aebab214a9f2a5f366d25e10ac3de0fbc4c35892ea6695d2faae4c8f835509c9bc8356dd134fe571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
