theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
toolbar:
  - insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image |  preview media fullpage | forecolor backcolor emoticons codesample
plugins:
  - advlist
  - autolink
  - link
  - image
  - lists
  - charmap
  - preview
  - hr
  - anchor
  - pagebreak
  - spellchecker
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
  - fullscreen
  - insertdatetime
  - media
  - nonbreaking
  - save
  - table
  - contextmenu
  - directionality
  - emoticons
  - template
  - paste
  - textcolor
  - codesample
menubar: false
statusbar: false
